### ISSUE TITLE
有关爬虫爬取的接口问题

### ISSUE THREAD

**Issue by whGodgilla** [Laichj/box-spider#1]
大佬能给下接口的信息吗？目前自己搭建了您的项目，交易日判断那一块没有弄明白。目前正在观察k线数据那块的接口。
想请问一下，有没有爬取股票其他信息的接口，比如股票的市盈率，包括f10里的一些信息，比如财务报表之类的，筹码分布数据这类接口呢。

**Comment by Laichj** [comment]
这个项目里交易日判断是通过每天定时拉去中国平安的股票状态，如果是开市状态则将今天的日期添加到开始记录中。
项目的基本架构已经搭起来，其他的一些股票信息参考已有模块都是可以快速实现的，有兴趣可以搞搞
